### ISSUE TITLE
Course Curriculum and Materials: about Design Language / the IBM Design Language (Grid, color, type, motion)

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/issue-tracking#114]

**Comment by jeanservaas** [comment]
Not stale

**Comment by jeanservaas** [comment]
## Carbon Patterns Coursework

Keynote file:
https://ibm.box.com/s/uhzy7z2tbks2s6dcv9xjrk23ohhrc13a

<br>

**The work represented here:**

- [x] Consolidate, trim down and refresh IBM Design Essentials materials with an eye towards relevancy to Product

<br>

_Note: I did not include motion content and I did not incorporate the Essentials course on the Design kit since most of what @aagonzales and Erica covered had to do with box drive which is now irrelevant._

<br>

**Still needs to be done:**

- [ ] **Create exercises:** Need to make this content more interactive for a workshop format; where / how do we want to add break out sessions or activities

- [ ] Add "Set up Sketch environment" / kit and symbol intro content 

- [ ] How will we incorporate "Code tooling" content? @mattrosno 's Dev Essentials content is not represented here

- [ ] Is there more we want to say about Patterns, Add ons, the contribution model and Carbon governance?

Related to #115
