### ISSUE TITLE
Retro: Rethink how we are doing support

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/issue-tracking#123]
> _This issue was created from the "New ideas to try" list in our October retro. Feel free to update the description and assignees if needed._

- [ ] Formally define the scope and intent of the support project and externalize our model to our community. Some ideas include having 1 week rotations on support.
- [ ] Write down the expected outcomes for the support team project.

**Comment by joshblack** [comment]
One reason we pitched support as a project was because there are efforts that span longer than one week. Limiting time on support to one week would mean that only fixes scoped within that time frame could be handled versus longer arching ones that may need to be addressed system-wide. Another opportunity of this support team could be to invest in building tooling that helps make support even more successful in the future
