### ISSUE TITLE
Content Switcher - experimental component (feedback from review)

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/issue-tracking#65]
- [ ] Need to have a 40 px option
- [ ] Text needs to left align (16 px from left side)
- [ ] Incorporate corner radius (0;4;4;0)

**Comment by joshblack** [comment]
Hey @laurenmrice! 👋 Taking a look at this now, had a couple of questions:

>  Text needs to left align (16 px from left side)

Since the content in the tabs can change depending on what the user provides, I'm not sure how we could have them appeared left aligned. In the sketch file it seems like each tab is set to the size of the largest tab (32px) but we would be unable to replicate this effect without using JavaScript.

We could have each tab span 100% of the available width and left-align it that way, but then the tabs might appear too large for the desired effect here. For example:

![image](https://user-images.githubusercontent.com/3901764/51862408-2ccd3c80-2304-11e9-8b6e-2a8b891b5158.png)

>  Need to have a 40 px option

Is there a sketch file I could reference for this option? Is it just having the height of the control set to 40px instead of 32px? Also, what are we naming this variant?

>  Incorporate corner radius (0;4;4;0)

Is this for the last tab in the tab list, and then the first tab would be `4;0;0;4`?

**Comment by laurenmrice** [comment]
So you are saying that without javascript we can still span 100% of the available width. Does this mean that we can still do this below? 
![specs](https://user-images.githubusercontent.com/43969356/51867932-59885080-2312-11e9-98ae-f4896b590e21.png)
You would apply the longest width needed for one section across all other sections? This is the desired state to have all sections an equal width regardless of the text length inside.

**Comment by asudoh** [comment]
Moved to: IBM/carbon-components#1863
